name: Run Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test || true
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: |
            errorPhotos/
            successPhotos/
