name: Run Playwright Tests

on:
  workflow_dispatch:   # <-- позволяет запускать вручную
  repository_dispatch: # <-- позволяет запускать из Telegram

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

